// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ2b-VVsLZsheUN--P_-QdP6UwulLhB4w',
    appId: '1:612442301144:web:b5a264603eff5be3332dad',
    messagingSenderId: '612442301144',
    projectId: 'suuq-4b572',
    authDomain: 'suuq-4b572.firebaseapp.com',
    storageBucket: 'suuq-4b572.appspot.com',
    measurementId: 'G-YVMV3GRHM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALwn6CdBMVummiSu64rstx1iNWi0kEQ-Y',
    appId: '1:612442301144:android:129be11d0b021bc6332dad',
    messagingSenderId: '612442301144',
    projectId: 'suuq-4b572',
    storageBucket: 'suuq-4b572.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDehpSgAAzHEjzlJ7MXK5m8KuOA-K533tY',
    appId: '1:612442301144:ios:686cfd8c2f894f7a332dad',
    messagingSenderId: '612442301144',
    projectId: 'suuq-4b572',
    storageBucket: 'suuq-4b572.appspot.com',
    iosBundleId: 'com.example.suuq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDehpSgAAzHEjzlJ7MXK5m8KuOA-K533tY',
    appId: '1:612442301144:ios:686cfd8c2f894f7a332dad',
    messagingSenderId: '612442301144',
    projectId: 'suuq-4b572',
    storageBucket: 'suuq-4b572.appspot.com',
    iosBundleId: 'com.example.suuq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ2b-VVsLZsheUN--P_-QdP6UwulLhB4w',
    appId: '1:612442301144:web:ed730b7fcd87f983332dad',
    messagingSenderId: '612442301144',
    projectId: 'suuq-4b572',
    authDomain: 'suuq-4b572.firebaseapp.com',
    storageBucket: 'suuq-4b572.appspot.com',
    measurementId: 'G-4S3YG48ZKJ',
  );
}
